# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 291defb28f784aefa97de8a3b6b6d713668ce697917b3b0cfc1218d384a9b6fec4cd770a5e8409682415141ac8c6a052f8e17d62d186c8bbc9123f276dae45ab

test:
  secret_key_base: ed787a8b42013860fa916538975527189d2750eafc3d9cdcff3848ef61913b2839945a7e41bc48634dbfeebf50316212c56cf18485d7c0f49f9ac6bd1406cf69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
